#@data/values
---
mysql:
  enabled: true
  values:
    primary:
      persistence:
        size: 1Gi

postgres:
  enabled: true  
  values:
    primary:
      persistence:
        size: 1Gi

rabbitmq:
  enabled: true  
  values:
    persistence:
      size: 1Gi

elasticsearch:
  enabled: true  
  values:
    master:
      persistence:
        size: 1Gi

redis:
  enabled: true
