#@data/values
---
mysql:
  enabled: true
  values:
    primary:
      persistence:
        size: 1Gi	

postgres:
  enabled: true  
  values:
    primary:
      persistence:
        size: 1Gi
    metrics:
      enabled: true

rabbitmq:
  enabled: true  
  values:
    persistence:
      size: 1Gi

elasticsearch:
  enabled: true  
  values:
    persistence:
      size: 1Gi

redis:
  enabled: true  
