name: push
on: ['push']

jobs:

  Service:
    uses: filipeforattini/ff-iac-github-actions/.github/workflows/service-push.yml@main
    with:
      debug: true
      mainBranch: main
      platforms: linux/amd64,linux/arm/v8,linux/arm64
      autoVersioning: false
      containerRegistry: ghcr.io
      environmentsAsNamespaces: false
    secrets: inherit

  Outputs:
    runs-on: ubuntu-latest
    needs: Service
    steps:
      - run: echo PipelineSetup = ${{ needs.Service.outputs.PipelineConfig }}
