name: ff-svc-pipetest
on: ['push']

jobs:

  Service:
    uses: filipeforattini/ff-iac-github-actions/.github/workflows/service-push.yml@v1.0.2
    with:
      mainBranch: main
      containerRegistry: ghcr.io

  Outputs:
    runs-on: ubuntu-latest
    needs: Service
    steps:
      - run: echo PipelineSetup = ${{ needs.Service.outputs.PipelineConfig }}
