name: ff-svc-pipetest
on: ['push']

jobs:

  Service:
    uses: filipeforattini/ff-iac-github-actions/.github/workflows/service-push.yml@main
    with:
      mainBranch: main
      containerRegistry: ghcr.io
      secretsDriver: actions
      secrets: |
        echo '{
          "A": "${{ secrets.A }}",
          "B": "${{ secrets.B }}",
          "C": "${{ secrets.B }}",
        }' | base64

  Outputs:
    runs-on: ubuntu-latest
    needs: Service
    steps:
      - run: echo PipelineSetup = ${{ needs.Service.outputs.PipelineConfig }}
