name: ff-svc-pipetest
on: ['push']

jobs:

  Service:
    uses: filipeforattini/ff-iac-github-actions/.github/workflows/service-push.yml@v1.3.7
    with:
      mainBranch: main
      containerRegistry: ghcr.io
    secrets: inherit

  Outputs:
    runs-on: ubuntu-latest
    needs: Service
    steps:
      - run: echo PipelineSetup = ${{ needs.Service.outputs.PipelineConfig }}
