name: ff-svc-pipetest
on: ['push']

jobs:

  Service:
    uses: filipeforattini/ff-iac-github-actions/.github/workflows/service-push.yml@v1.10.1
    with:
      debug: true
      mainBranch: main
      platforms: linux/amd64,linux/arm/v8,linux/arm64
      containerRegistry: ghcr.io
    secrets: inherit

  Outputs:
    runs-on: ubuntu-latest
    needs: Service
    steps:
      - run: echo PipelineSetup = ${{ needs.Service.outputs.PipelineConfig }}
