name: ff-svc-pipetest
on: ['push']

jobs:

  Service:
    uses: filipeforattini/ff-iac-github-actions/.github/workflows/service-push.yml@v1.2.5
    with:
      mainBranch: main
      containerRegistry: ghcr.io
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_DEV_PASSPHRASE: ${{ secrets.GPG_DEV_PASSPHRASE }}
      GPG_STG_PASSPHRASE: ${{ secrets.GPG_STG_PASSPHRASE }}
      GPG_PRD_PASSPHRASE: ${{ secrets.GPG_PRD_PASSPHRASE }}

  Outputs:
    runs-on: ubuntu-latest
    needs: Service
    steps:
      - run: echo PipelineSetup = ${{ needs.Service.outputs.PipelineConfig }}
